name: Run Tests

on:
  workflow_run:
    workflows: ["Check Code Style"]  # This references the workflow that should be completed before running this one
    types:
      - completed

jobs:
  test_no_env:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  # Runs on Linux, Windows, and macOS
        python-version: ['3.12']  # The latest 5 Python versions
      fail-fast: false  # Continue testing other platforms even if one fails
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (without virtual environment)
        run: |
          pip install -r ./requirements.txt

      - name: List all files and dirs in root
        run: |
          echo "In Root:"
          ls -a /
          echo "In /home:"
          ls -a /home
          echo "In /home/runner:"
          ls -a /home/runner/
          echo "In ~:"
          ls -a ~
          echo "In Current:"
          ls -a .
  
      - name: Run tests
        run: |
          pytest tests/

  test_conda:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  # Runs on Linux, Windows, and macOS
        python-version: ['3.12', '3.13']  # The latest 5 Python versions
      fail-fast: false  # Continue testing other platforms even if one fails
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: logger
          auto-activate-base: false
          auto-update-conda: true
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}

      - name: Check conda env parameter
        run: |
          echo "conda path: $CONDA"

      - name: Cache conda packages
        id: cache-conda-packages
        uses: actions/cache@v4
        with:
          path: |
            ~/conda_pkgs_dir
            ${{ env.CONDA }}/pkgs
          key: conda-packages-${{ runner.os }}-python-${{ matrix.python-version }}-${{ hashFiles('environment.yml') }}
          restore-keys: conda-packages-${{ runner.os }}-python-${{ matrix.python-version }}-

      - name: List all files and dirs in root
        run: |
          echo "In Root:"
          ls -a /
          echo "In /home:"
          ls -a /home
          echo "In /home/runner:"
          ls -a /home/runner/
          echo "In ~:"
          ls -a ~
          echo "In Current:"
          ls -a .

      - name: Setup conda environment and run tests
        run: |
          conda init
          source ~/.bashrc
          source "$CONDA/etc/profile.d/conda.sh"
          conda info
          conda env list
          conda activate logger
          conda env update -f ./environment.yml
          pytest tests/
