name: Run Tests

on:
  workflow_run:
    workflows: ["Check Code Style"]  # This references the workflow that should be completed before running this one
    types:
      - completed

jobs:
  test_no_env:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  # Runs on Linux, Windows, and macOS
        python-version: ['3.12']  # The latest 5 Python versions
      fail-fast: false  # Continue testing other platforms even if one fails
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: List all files and dirs in root
        run: |
          echo "In Root:"
          ls -a /
          echo "In /home:"
          ls -a /home
          echo "In /home/runner:"
          ls -a /home/runner/
          echo "In ~:"
          ls -a ~
          echo "In Current:"
          ls -a .

      - name: Install dependencies (without virtual environment)
        run: |
          pip install -r ./requirements.txt

      - name: Run tests
        run: |
          pytest tests/

  test_conda:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  # Runs on Linux, Windows, and macOS
        python-version: ['3.12']  # The latest 5 Python versions
      fail-fast: false  # Continue testing other platforms even if one fails
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: logger

      - name: List all files and dirs in root
        run: |
          echo "In Root:"
          ls -a /
          echo "In /home:"
          ls -a /home
          echo "In /home/runner:"
          ls -a /home/runner/
          echo "In ~:"
          ls -a ~
          echo "In Current:"
          ls -a .

      - name: Initialise conda
        run: |
          conda init

      - name: Update shell
        run: |
          source ~/.bashrc

      - name: Print conda info
        run: |
          conda info

      - name: List conda environments
        run: |
          conda env list

      - name: Activate logger environment
        run: |
          conda init
          source ~/.bashrc
          conda env list
          conda activate logger

      - name: Update the conda environment and reactivate logger environment
        run: |
          conda env update -f ./environment.yml
          conda activate logger

      - name: Run tests
        run: |
          pytest tests/
